version: '3'

services:
  portainer-agent:
    container_name: portainer-agent
    image: portainer/agent:1.5.1
    volumes:
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9001:9001"
    logging:
      driver: journald
      options:
        tag: portainer-agent
  
  homeassistant:
    container_name: home-assistant
    #image: homeassistant/raspberrypi3-homeassistant:0.118.4    
    image: homeassistant/raspberrypi3-homeassistant:2021.4.6
    restart: unless-stopped
    logging:
      driver: journald
      options:
        tag: homeassistant
    devices:
      # - /dev/serial/by-id/usb-0658_0200-if00:/dev/serial/by-id/usb-0658_0200-if00
      - /dev/serial/by-id/usb-0658_0200-if00:/dev/usbzwave
    volumes:
      - /srv/docker/hass-config:/config
      - /etc/localtime:/etc/localtime:ro
      - /srv/docker/hass_media:/media
      - /home/pi/git/docker-has/hass-config:/home/pi/git/docker-has/hass-config:ro
    network_mode: host
    ports:
      - "8123:8123"
