homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret home_name
 
  # Location required to calculate the time the sun rises and sets
 
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  
  unit_system: metric

  # Impacts weather/sunrise data
  elevation: !secret home_elevation
  temperature_unit: C
  time_zone: !secret home_timezone

  customize:
    binary_sensor.fibaro_system_fgk101_door_opening_sensor_sensor:
      friendly_name: Hallen
      device_class: door
    sensor.yr_cloudiness:
      friendly_name: Molnighet
    sensor.yr_wind_direction:
      friendly_name: Vind Riktning
    sensor.yr_wind_speed:
      friendly_name: Vind Hastighet
    sensor.yr_pressure:
      friendly_name: Lufttryck
    sensor.yr_symbol:
      friendly_name: Prognos
    sensor.yr_humidity:
      friendly_name: Luftfuktighet
    sensor.yr_precipitation:
      friendly_name: Regn
    sensor.temperatur_nu:
      icon: mdi:temperature-celsius
    switch.switch_1:
      friendly_name: 'TV:n'
      icon: mdi:lightbulb-on 
      device_class: light
    switch.switch_2:
      friendly_name: 'Köksfönstret'
      icon: mdi:lightbulb-on 
      device_class: light
    switch.switch_3:
      friendly_name: 'Ebbas Rum'
      icon: mdi:lightbulb-on 
      device_class: light
    switch.switch_4:
      friendly_name: 'Julgranen'
      icon: mdi:lightbulb-on
      device_class: light
    switch.switch_5:
      friendly_name: 'Lampa Hallen'
      icon: mdi:lightbulb-on
      device_class: light
    switch.switch_6:
      friendly_name: 'Ebbas Fönster'
      icon: mdi:lightbulb-on
      device_class: light

  auth_providers:
    - type: trusted_networks
      trusted_networks:      
        - 127.0.0.1
        - !secret http_trust
    - type: homeassistant

#icon: mdi:lightbulb-on
 

# Show links to resources in log and frontend
#introduction:

# Enables support for tracking state changes over time.
history:

# Track the sun
sun:

# Checks for available updates
updater:
  reporting: false

config:

system_health:

mobile_app:

# Enables the frontend
frontend:

# Allows you to issue voice commands from the frontend
#conversation:

# Discover some devices automatically
#discovery:

# View all events in a logbook
logbook:

influxdb:
  host: !secret influxdb_host
  database: !secret influxdb_database
  username: !secret influxdb_username
  password: !secret influxdb_password

zwave:
  polling_interval: 60000
  usb_path: /dev/usbzwave

variable:
  door_counter:
    value: 0
    restore: false
    attributes:
      friendly_name: 'Door Counter'
      icon: mdi:counter

shell_command:
  tell_hallonet: '/config/scripts/zmagnet.sh {{to}}'

# Includes

sensor: !include_dir_list sensors/
switch: !include_dir_list switches/
#automation: !include automations.yaml

automation:
  - alias: Hallen Door
    trigger:
      platform: state
      entity_id: binary_sensor.fibaro_system_fgk101_door_opening_sensor_sensor
    action:
      - service: shell_command.tell_hallonet
        data_template:
          to: '{{ trigger.to_state.state }}'
      - condition: state
        entity_id: binary_sensor.fibaro_system_fgk101_door_opening_sensor_sensor
        state: 'on'
      - service: variable.set_variable
        data:
          variable: door_counter
          value_template: '{{ (variable.state | int) + 1 }}'
#  - alias: Hallen Light On
#    trigger:
#      platform: time
#      at: "05:45:00"
#    action:
#      - service: switch.turn_on
#        entity_id: switch.switch_5

group:
  default_view:
    name: Ripstigen
    #view: no
    entities:
      - binary_sensor.fibaro_system_fgk101_door_opening_sensor_sensor
      - sensor.temperatur_nu
      - variable.door_counter
      - switch.switch_1
      - switch.switch_2
      - switch.switch_3
      - switch.switch_4
      - switch.switch_5
      - switch.switch_6
  yr:
    name: YR
    #view: no
    entities:
      - sensor.yr_symbol
      - sensor.yr_cloudiness
      - sensor.yr_pressure
      - sensor.yr_precipitation
      - sensor.yr_humidity      
      - sensor.yr_wind_direction
      - sensor.yr_wind_speed

  speedtestdotnet:
    name: Speedtest
    #view: no
    entities:
      - sensor.speedtest_ping
      - sensor.speedtest_download
      - sensor.speedtest_upload

speedtestdotnet:
  scan_interval:
    minutes: 30
    hours: 6
  monitored_conditions:
    - ping
    - download
    - upload



